# Generated by Django 4.1.13 on 2024-02-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_previous_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sexe',
            new_name='statue',
        ),
    ]
