# Generated by Django 4.1.13 on 2024-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_sexe_user_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='statue',
            new_name='statut',
        ),
    ]
