# Generated by Django 4.1.13 on 2024-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_statue_user_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
