# Generated by Django 4.1.13 on 2024-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
